version: '3.8'

services:
  app-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODEL_URL: "https://drive.google.com/uc?id=<your-file-id>"
    ports:
      - "5000:5000"
