version: '3.8'

services:
  app-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MODEL_URL=https://path_to_model_storage/model.joblib
