version: '3.3'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      MODEL_SERVICE_URL: http://model-service:5000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:5001

  model-service:
    image: your-dockerhub-username/model-service:latest
    ports:
      - "5000:5000"
